name: Update and Deploy SiteContainers to Azure Web App
on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: "read"
    packages: "write"

env:
    AZURE_WEBAPP_NAME: "yagnik-apps-monitoring"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.REGISTRY_SERVER_PASSWORD }}

            - name: Build Nginx container
              uses: docker/build-push-action@v6
              with:
                  file: Dockerfile.nginx
                  push: true
                  tags: ghcr.io/${{ github.repository_owner }}/nginx-configured:latest

            - name: Build Prometheus container
              uses: docker/build-push-action@v6
              with:
                  file: Dockerfile.prometheus
                  push: true
                  tags: ghcr.io/${{ github.repository_owner }}/prometheus-configured:latest

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Configure GHCR credentials on Azure Web App
              uses: azure/appservice-settings@v1
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  app-settings-json: |
                      [
                        {"name": "DOCKER_REGISTRY_SERVER_URL", "value": "https://ghcr.io"},
                        {"name": "DOCKER_REGISTRY_SERVER_USERNAME", "value": "${{ github.actor }}"},
                        {"name": "DOCKER_REGISTRY_SERVER_PASSWORD", "value": "${{ secrets.REGISTRY_SERVER_PASSWORD }}"}
                      ]

            - name: Deploy multi-container app
              uses: azure/webapps-deploy@v2
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  sitecontainers-config: >-
                      [
                      	{
                          "name": "nginx",
                          "image": "ghcr.io/${{ github.repository_owner }}/nginx-configured:latest",
                          "targetPort": 80,
                          "isMain": true
                        },
                      	{
                          "name": "prometheus",
                          "image": "ghcr.io/${{ github.repository_owner }}/prometheus-configured:latest",
                          "targetPort": 9090,
                          "isMain": false,
                          "volumeMounts": [{"name": "prometheus", "mountPath": "/prometheus"}]
                        },
                        {
                          "name": "grafana",
                          "image": "grafana/grafana:latest",
                          "targetPort": 3000,
                          "isMain": false,
                          "volumeMounts": [{"name": "grafana", "mountPath": "/var/lib/grafana"}],
                          "environmentVariables": [
                              {"name": "GF_SECURITY_ADMIN_USER", "value": "${{ secrets.GF_SECURITY_ADMIN_USER }}"},
                              {"name": "GF_SECURITY_ADMIN_PASSWORD", "value": "${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}"}
                              ]
                        }
                      ]
